### PR TITLE
README and bootstrap overhaul

### PR DESCRIPTION
**Pull request by erri120**
- updated all dependencies to a version that will actually produce a successful build
- added more information on what and how to download
- updated the `bootstrap.ps1`
- new `README.md` is common markdown syntax complient

### CODE REVIEW

**Comment by TanninOne** [comment]
Hi erri120,

thanks for the bugfixes. However I'm not happy with the removal of the entire git clone/build step. The bootstrap script is supposed to get everything to a fully finished state where you can then immediately run the development version of Vortex.
Ideally people wouldn't need to know how git and yarn commandline tools work until the point where they already have a working build and can replicate what our script does.

**Comment by erri120** [comment]
Shouldn't you first fork the project, clone the fork and work with that?

**Comment by TanninOne** [comment]
I'm not sure why this would make a difference, if you fork Vortex it would still help having a bootstrap script that builds everything.
Surely you would verify you can build the thing before you start making changes.

Besides: Considering how modular Vortex is, it would make sense to build a vanilla Vortex and then build on an extension, without actually modifying the main application.

**Comment by erri120** [comment]
There updated, the script will clone the repository if does not detect `package.json` in the current output folder so that ppl who forked and cloned the repo already do not download vortex again

**Comment by TanninOne** [comment]
Thank you for the update. I have to test the script before I merge and I won't be able to until monday so please excuse the delay.

Also: Why did you change the instructions to run "npm install --global yarn" in an elevated shell? It should work just fine for the restricted user?

**Comment by thetric** [comment]
Just FYI:

- Python 2 is deprecated since 2020-01-01: https://www.python.org/doc/sunset-python-2/. I'm trying Python 3.8.1 but it fails due to a newer MS Build Tools version.
- MS Build Tools 2019 are available but `yarn install` fails:

```
error C:\Users\me\github\vortex\node_modules\fomod-installer: Command failed.
Exit code: 1
Command: npm run build
Arguments:
Directory: C:\Users\me\github\vortex\node_modules\fomod-installer
Output:
> fomod-installer@0.3.0 build C:\Users\me\github\vortex\node_modules\fomod-installer
> node build.js && copyfiles -f Build/bin/Release/*.dll dist/

  build starting
events.js:187
      throw er; // Unhandled 'error' event
      ^

Error: spawn C:\WINDOWS\microsoft.net\Framework64\v15.0\msbuild.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn C:\\WINDOWS\\microsoft.net\\Framework64\\v15.0\\msbuild.exe',
  path: 'C:\\WINDOWS\\microsoft.net\\Framework64\\v15.0\\msbuild.exe',
  spawnargs: [
    'C:\\Users\\me\\github\\vortex\\node_modules\\fomod-installer',
    '/p:configuration=Release;TargetFrameworkVersion=v4.5',
    '/t:restore'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fomod-installer@0.3.0 build: `node build.js && copyfiles -f Build/bin/Release/*.dll dist/`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fomod-installer@0.3.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Pull request closed without merging**
